config/routes.rb
Spree::Core::Engine.routes.prepend do

  match '/blog',                              :to => 'articles#index',   :as => 'blog_articles'
  match '/blog.:format',                      :to => 'articles#index',   :as => 'blog_articles'
  match '/blog/tag/:tag',                     :to => 'articles#tag',     :as => 'blog_tag'
  match '/blog/page/:page',                   :to => 'articles#index',   :as => 'blog_articles_page'
  match '/blog/:year/:month',                 :to => 'articles#archive', :as => 'blog_articles_archive'
  match '/blog/:year/:month/:day/:permalink', :to => 'articles#show',    :as => 'blog_article'

end

app/models/article.rb
class Article < FileModel
  
  def self.find_articles(options = {})
    options = {
      :per_page => 10,
      :page => 1
    }.merge(options)
    
    options[:offset] = (options[:page]-1) * options[:per_page]
    options[:limit] = options[:per_page]

    if options[:year] and options[:month]
      options[:match] = %r(\/#{options[:year]}-#{options[:month].to_s.rjust(2,'0')})
    end

    all(options)
  end

  def self.recent(number = 5)
    @@recent ||= all(:limit => number)
  end

  def self.tagged(tag) 
    tag_index[tag.strip].to_a.map do |key|
      Article.find(key)
    end
  end

  def self.archive_months
    @@archive_months ||= files.map{|f| File.basename(f).split('-')[0..1] }.uniq
  end

  # Store list of articles for each tag in a hash
  # Fast enough for the small number of articles we're dealing with
  @@tag_index = {}
  def self.tag_index
    return @@tag_index if @@tag_index.present?
    all.each do |a| 
     a.tags.split(',').map(&:strip).each do |t| 
       @@tag_index[t] ||= []
       @@tag_index[t] = (@@tag_index[t] << a.key).uniq
      end
    end
    @@tag_index
  end
  
  %w(title_tag meta_keywords meta_description).each do |attribute|
    define_method(attribute) do
      meta[attribute]
    end
  end

end

app/models/file_model.rb
# Base class for simple models that load their content from text files formatted like Toto's articles
class FileModel
  attr_accessor :file, :key, :meta, :body
  
  def initialize(file, key, meta, body)
    @file = file
    @key = key
    @meta = meta
    @body = body  
  end

  def method_missing(method, *args)
    if meta.has_key?(method.to_s)
      meta[method.to_s]
    else
      super
    end
  end


  def self.all(options = {})
    options = {
      :offset => 0
    }.merge(options)

    files = get_filtered_files(options)

    if options[:limit]
      files = files[options[:offset] .. (options[:offset].to_i + options[:limit].to_i-1)]
    end

    records = files.to_a.map do |f|
      from_file(f)
    end

    records
  end

  def self.find(key)
    from_file("#{content_path}/#{key}.txt")
  end
  
  def self.count(options = {})
    get_filtered_files(options).length
  end
  
  def self.random(options = {})
    from_file(files[rand(all.size)])
  end

  def self.files
    Dir["#{content_path}/*.txt"].sort_by {|f| File.basename(f) }.reverse
  end

  def index
    @index ||= self.class.files.index(file)
  end

  def next
    return @next if @next.present?
    if next_file = self.class.files[index + 1]
      @next = self.class.from_file(next_file)
    end
  end

  def previous
    return @previous if @previous.present?
    if index > 0 and previous_file = self.class.files[index - 1]
      @previous = self.class.from_file(previous_file)
    end
  end

  def self.from_file(file)
    meta, body = File.read(file).split(/\n\n/, 2)
    meta = YAML.load(meta)
    key = File.basename(file).gsub('.txt','')
    new(file, key, meta, body)
  end

  def self.content_path
    File.expand_path(File.join(Rails.root, "content",  relative_path))
  end

  def self.relative_path
    self.name.underscore
  end
  
  private
  
    def self.get_filtered_files(options)
      if options[:match]
        files.select{|f| f =~ options[:match]}
      else
        files
      end
    end
    
end

app/models/simple_blog_configuration.rb
class SimpleBlogConfiguration  < Spree::Preferences::Configuration

  preference :disqus_id, :string, :default => ''
  preference :blog_feed_url, :string, :default => '/blog.xml'

end

app/controllers/articles_controller.rb
class ArticlesController < Spree::BaseController
  rescue_from  Errno::ENOENT, :with => :render_404
  
  def index
    @per_page = 10
    @current_page = (params[:page] || 1).to_i
    @total_pages = (Article.count / @per_page.to_f).ceil
    @articles = Article.find_articles(:page => @current_page)
    respond_to do |wants|
      wants.html {}
      wants.xml {}
    end
  end
  
  def archive
    @articles = Article.find_articles(:year => params[:year], :month => params[:month])
    render :action => 'index'
  end
  
  def tag
    @articles = Article.tagged(params[:tag])
    render :action => 'index'
  end
  
  def show
    key = "#{params[:year]}-#{params[:month].rjust(2,'0')}-#{params[:day].rjust(2,'0')}-#{params[:permalink]}"
    @article = Article.find(key)
  end
  
end

app/controllers/spree/articles_controller.rb
class Spree::ArticlesController < Spree::BaseController
  rescue_from  Errno::ENOENT, :with => :render_404

  def index
    @per_page = 10
    @current_page = (params[:page] || 1).to_i
    @total_pages = (Article.count / @per_page.to_f).ceil
    @articles = Article.find_articles(:page => @current_page)
    respond_to do |wants|
      wants.html {}
      wants.xml {}
    end
  end

  def archive
    @articles = Article.find_articles(:year => params[:year], :month => params[:month])
    render :action => 'index'
  end

  def tag
    @articles = Article.tagged(params[:tag])
    render :action => 'index'
  end

  def show
    key = "#{params[:year]}-#{params[:month].rjust(2,'0')}-#{params[:day].rjust(2,'0')}-#{params[:permalink]}"
    @article = Article.find(key)
  end

end

app/helpers/articles_helper.rb
require 'rdiscount'

module ArticlesHelper
  
  def html_transform(text)
    RDiscount.new(text.to_s).to_html.html_safe
  end

  def format_date(time)
    time.strftime("%B %d %Y")
  end

  def format_time(time)
    time.strftime("%I:%m%p")
  end

  def link_to_archive(archive_month)
    text = "#{Date::MONTHNAMES[archive_month.last.to_i]} #{archive_month.first.to_i}"
    link_to text, blog_articles_archive_url(:year => archive_month.first, :month => archive_month.last.to_s.rjust(2, '0'))
  end

  def link_to_article(article, options = {})
    link_to h(article.title), article_url(article), options
  end
  
  def article_url(article)
    blog_article_url :permalink => article.slug, :year => article.date.year, :month => article.date.month, :day => article.date.day
  end

  def url_escape(string)
    string.gsub(/([^ a-zA-Z0-9_.-]+)/n) do
      '%' + $1.unpack('H2' * $1.size).join('%').upcase
    end.tr(' ', '+')
  end
  
end

app/views/articles/_comment_count_js.html.erb
<% if Spree::Config[:disqus_id] %>
  <% content_for :extra_javascripts do %>
    <script type="text/javascript">
    //<![CDATA[
    (function() {
    	var links = document.getElementsByTagName('a');
    	var query = '?';
    	for(var i = 0; i < links.length; i++) {
    	if(links[i].href.indexOf('#disqus_thread') >= 0) {
    		query += 'url' + i + '=' + encodeURIComponent(links[i].href) + '&';
    	}
    	}
    	document.write('<script charset="utf-8" type="text/javascript" src="http://disqus.com/forums/<%= Spree::Config[:disqus_id] %>/get_num_replies.js' + query + '"></' + 'script>');
    })();
    //]]>
    </script>
  <% end %>
<% end %>

app/views/articles/show.html.erb
<% self.title = "Blog - " + @article.title %>
<% @body_class = 'blog' %>

<div class="navigation">
  <% if @article.previous %>
	<div class="alignleft">&laquo; <%= link_to_article @article.previous %></div>
	<% end %>
  <% if @article.next %>
	<div class="alignright"><%= link_to_article @article.next %> &raquo;</div>
	<% end %>
	<br class="clear" />
</div>

<%= render 'article', :article => @article %>

<% if Spree::Config[:disqus_id] %>
<div id="comments">
  <a name="respond"></a>
  <div id="disqus_thread"></div>
  <script type="text/javascript">
    var disqus_developer = <%= RAILS_ENV == 'development' ? '1' : '0' %>;
  </script>
  <noscript><a href="http://spreecommerce.disqus.com/?url=ref">View the discussion thread.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
<% end %>



<% content_for :sidebar do %>
  <%= render 'sidebar' %>
<% end %>

<% if Spree::Config[:disqus_id] %>
  <% content_for :extra_javascripts do %>
    <script type="text/javascript" src="http://disqus.com/forums/<%= Spree::Config[:disqus_id] %>/embed.js"></script>
  <% end %>
<% end %>

app/views/spree/articles/_archives.html.erb
<div id="archives">
  <h2>Archives</h2>
  <ul>
    <% for archive_month in Article.archive_months %>
  		<li><%= link_to_archive archive_month %></li>
		<% end %>
	</ul>
</div>

app/views/spree/articles/_article.html.erb
<div class="post">

  <div class="heading">
    <h2><%= link_to_article article %></h2>
    <p>
      <span class="author">by <strong><%= article.author %></strong></span>
      &bull;
      <span class="date"><%= format_date article.date %></span> 
    </p>
  </div>

  <div class="entry">

    <%= html_transform article.body %>

  </div>
  
  <% if @articles %>
  <div class="meta">
    <p class="comments"><a href="<%= article_url article %>#respond" title="Comment on <%= article.title %>">Comments &#187;</a></p>
    <p class="time">Posted @ <%= format_time article.date %></p>
    <br class="clear" />
  </div>
  <% else %>
    <% if @article.tags.present? %>
    <p>Tags: 
      <%= @article.tags.split(',').map { |tag|  link_to(tag, blog_tag_path(tag), :rel => 'tag')}.join(', ') %>
    <% end %>
  <% end %>

</div>

app/views/spree/articles/_comment_count_js.html.erb
<% if SimpleBlogExtension::Config.disqus_id.present? %>
  <% content_for :extra_javascripts do %>
    <script type="text/javascript">
    //<![CDATA[
    (function() {
    	var links = document.getElementsByTagName('a');
    	var query = '?';
    	for(var i = 0; i < links.length; i++) {
    	if(links[i].href.indexOf('#disqus_thread') >= 0) {
    		query += 'url' + i + '=' + encodeURIComponent(links[i].href) + '&';
    	}
    	}
    	document.write('<script charset="utf-8" type="text/javascript" src="http://disqus.com/forums/<%= SimpleBlogExtension::Config.disqus_id %>/get_num_replies.js' + query + '"></' + 'script>');
    })();
    //]]>
    </script>
  <% end %>
<% end %>

app/views/spree/articles/_recent.html.erb
<div id="recent-posts">
  <h2>Recent Posts</h2>	
  <ul>
    <% for article in Article.recent %>
  		<li><%= link_to_article article %></li>
		<% end %>
	</ul>
</div>

app/views/spree/articles/_sidebar.html.erb
<% hook :blog_sidebar do %>

  <% if Spree::Config[:blog_feed_url] %>
    <%= render 'subscribe' %>
  <% end %>

  <%= render 'recent' %>

  <%= render 'archives' %>

<% end %>

app/views/spree/articles/_subscribe.html.erb
<div id="subscribe">
	<h2>Subscribe</h2>
	<ul>
		<li><a id="btnRss" href="<%= Spree::Config[:blog_feed_url] %>" title="Subscribe to the Railsdog RSS Feed">Railsdog RSS Feed</a></li>
	</ul>
</div>

app/views/spree/articles/index.html.erb
<% self.title = "Blog" %>
<% @body_class = 'blog' %>

<% if params[:tag] %>
	<h2 class="pagetitle">Posts Tagged &lsquo;<%= params[:tag] %>&rsquo;</h2>
<% elsif params[:year] && params[:month] %>
	<h2 class="pagetitle">Archive for <%= Date::MONTHNAMES[params[:month].to_i] %>, <%= params[:year].to_i %></h2>
<% end %>

<%= render :partial => 'article', :collection => @articles %>

<% if @total_pages %>
<div class="navigation">
  <% if @total_pages > 1 && @current_page < @total_pages %>
		<div class="alignleft"><a href="<%= url_for(:overwrite_params => {:page => @current_page + 1}) %>" >&laquo; Older Entries</a></div>
	<% end %>
	<% if @current_page > 1 %>
		<div class="alignright"><a href="<%= url_for(:overwrite_params => {:page => @current_page - 1}) %>" >Newer Entries &raquo;</a></div>
	<% end %>
	<br class="clear" />
</div>
<% end %>
	
<% content_for :sidebar do %>

  <%= render 'sidebar' %>

<% end %>

<br class="clear" />

app/views/spree/articles/show.html.erb
<% self.title = "Blog - " + @article.title %>
<% @body_class = 'blog' %>

<div class="navigation">
  <% if @article.previous %>
	<div class="alignleft">&laquo; <%= link_to_article @article.previous %></div>
	<% end %>
  <% if @article.next %>
	<div class="alignright"><%= link_to_article @article.next %> &raquo;</div>
	<% end %>
	<br class="clear" />
</div>

<%= render 'article', :article => @article %>

<% if SimpleBlogExtension::Config.disqus_id %>
<div id="comments">
  <a name="respond"></a>
  <div id="disqus_thread"></div>
  <script type="text/javascript">
    var disqus_developer = <%= RAILS_ENV == 'development' ? '1' : '0' %>;
  </script>
  <noscript><a href="http://spreecommerce.disqus.com/?url=ref">View the discussion thread.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
<% end %>



<% content_for :sidebar do %>
  <%= render 'sidebar' %>
<% end %>

<% if SimpleBlogExtension::Config.disqus_id %>
  <% content_for :extra_javascripts do %>
    <script type="text/javascript" src="http://disqus.com/forums/<%= SimpleBlogExtension::Config.disqus_id %>/embed.js"></script>
  <% end %>
<% end %>